spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/myapp
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 #페이징 처리를 위해 컬렉션은 in 절로 조회
    open-in-view: false

# 콘솔 창 색상 설정
  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.SQL: DEBUG
#    org.springframework.security: DEBUG
#    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret:
    key: akjbfiu23bfafnaji3889adskjndskjdsfnalaiweufh

server:
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: "always"
    include-stacktrace: "on_param"
    include-binding-errors: "on_param"